# Generated by Django 3.2.13 on 2026-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('avg_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('growth_rate', models.FloatField(blank=True, help_text='Expected growth rate in %, e.g. 12.5', null=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('required_skills', models.ManyToManyField(blank=True, related_name='careers', to='api.Skill')),
            ],
        ),
    ]
